require "bundler/setup"
require "eventmachine"

require_relative "../callback/callback"
require_relative "./lib/TCPHandler"
require_relative "./lib/UDPHandler"
require_relative "./lib/network_interface"
require_relative "./lib/command_messages"
require_relative "./lib/server"
require_relative "./lib/client"